nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['https://pacanele.herokuapp.com/','http://localhost/']
        allow_headers: ['Content-Type']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['https://pacanele.herokuapp.com/']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600